<?php

namespace OC\PlatformBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function classicFind()
	{
		$qb =  $this->createQueryBuilder('a')->orderBy('a.id', 'DESC');
		return $qb
		->getQuery()
		->getResult()
		;
	}

	public function complexFind($content)
	{
		$qb =  $this->createQueryBuilder('a');

		// transforme les caractère spéciaux (accents etc) en caractère html
		$content = htmlentities($content);
		

		$qb
		->Where('a.content LIKE :mot')
		->setParameter('mot', "%$content%")
		->orderBy('a.id', 'DESC')
		;

		return $qb
		->getQuery()
		->getResult()
		;
	}
}

