<?php

namespace OC\PlatformBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    // Get back and returns all blog's article
	public function classicFind()
	{
		$qb =  $this->createQueryBuilder('a')->orderBy('a.id', 'DESC');
		return $qb
		->getQuery()
		->getResult()
		;
	}

	// Get back and returns blog's articles matching a search
	public function complexFind($content)
	{
		$qb =  $this->createQueryBuilder('a');

		// Transforms special characters (accents etc) into html
		$content = htmlentities($content);

		$words = explode(" ", $content);

		$request = 'a.content LIKE :word OR a.title LIKE :word';

		for($i = 1; $i < count($words); ++$i) {

			$request = $request . ' OR a.content LIKE :word' . $i . ' OR a.title LIKE :word' . $i;
			
		}
		
		$qb
		->where($request)
		->setParameter('word', "%$words[0]%")
		;

		for($i = 1; $i < count($words); ++$i) {

			$qb
			->setParameter('word'. $i, "%$words[$i]%")
			;
			
		}

		$qb
		->orderBy('a.id', 'DESC')
		;

		return $qb
		->getQuery()
		->getResult()
		;
	}
}
